import QtQuick

QtObject {
    id: rootTemplate

    readonly property color background: "{{background}}"
    readonly property color surface: "{{surface}}"
    readonly property color surfaceBright: "{{surface_bright}}"
    readonly property color surfaceDim: "{{surface_dim}}"
    readonly property color surfaceTint: "{{surface_tint}}"
    readonly property color surfaceVariant: "{{surface_variant}}"
    readonly property color surfaceContainer: "{{surface_container}}"
    readonly property color surfaceContainerLow: "{{surface_container_low}}"
    readonly property color surfaceContainerLowest: "{{surface_container_lowest}}"
    readonly property color surfaceContainerHigh: "{{surface_container_high}}"
    readonly property color surfaceContainerHighest: "{{surface_container_highest}}"

    readonly property color primary: "{{primary}}"
    readonly property color primaryContainer: "{{primary_container}}"
    readonly property color primaryFixed: "{{primary_fixed}}"
    readonly property color primaryFixedDim: "{{primary_fixed_dim}}"
    readonly property color secondary: "{{secondary}}"
    readonly property color secondaryContainer: "{{secondary_container}}"
    readonly property color secondaryFixed: "{{secondary_fixed}}"
    readonly property color secondaryFixedDim: "{{secondary_fixed_dim}}"
    readonly property color tertiary: "{{tertiary}}"
    readonly property color tertiaryContainer: "{{tertiary_container}}"
    readonly property color tertiaryFixed: "{{tertiary_fixed}}"
    readonly property color tertiaryFixedDim: "{{tertiary_fixed_dim}}"

    readonly property color on_background: "{{on_background}}"
    readonly property color on_surface: "{{on_surface}}"
    readonly property color on_surface_variant: "{{on_surface_variant}}"
    readonly property color on_primary: "{{on_primary}}"
    readonly property color on_primary_container: "{{on_primary_container}}"
    readonly property color on_primary_fixed: "{{on_primary_fixed}}"
    readonly property color on_primary_fixed_variant: "{{on_primary_fixed_variant}}"
    readonly property color on_secondary: "{{on_secondary}}"
    readonly property color on_secondary_container: "{{on_secondary_container}}"
    readonly property color on_secondary_fixed: "{{on_secondary_fixed}}"
    readonly property color on_secondary_fixed_variant: "{{on_secondary_fixed_variant}}"
    readonly property color on_tertiary: "{{on_tertiary}}"
    readonly property color on_tertiary_container: "{{on_tertiary_container}}"
    readonly property color on_tertiary_fixed: "{{on_tertiary_fixed}}"
    readonly property color on_tertiary_fixed_variant: "{{on_tertiary_fixed_variant}}"
    readonly property color inverseSurface: "{{inverse_surface}}"
    readonly property color inverse_on_surface: "{{inverse_on_surface}}"
    readonly property color inversePrimary: "{{inverse_primary}}"

    readonly property color outline: "{{outline}}"
    readonly property color outlineVariant: "{{outline_variant}}"
    readonly property color shadow: "{{shadow}}"
    readonly property color scrim: "{{scrim}}"
    readonly property color error: "{{error}}"
    readonly property color errorContainer: "{{error_container}}"
    readonly property color on_error: "{{on_error}}"
    readonly property color on_error_container: "{{on_error_container}}"

    readonly property color sourceColor: "{{source_color}}"
    readonly property color warningColor: "{{warning}}"
    readonly property color successColor: "{{success}}"
}
