import QtQuick

QtObject {
    id: rootUnclaimedBloomColors

    readonly property color background: "#2e3440"
    readonly property color surface: "#3b4252"
    readonly property color surfaceBright: "#434c5e"
    readonly property color surfaceDim: "#242933"
    readonly property color surfaceTint: "#97a8d1"
    readonly property color surfaceVariant: "#4c566a"
    readonly property color surfaceContainer: "#2e3440"
    readonly property color surfaceContainerLow: "#242933"
    readonly property color surfaceContainerLowest: "#242933"
    readonly property color surfaceContainerHigh: "#434c5e"
    readonly property color surfaceContainerHighest: "#3b4252"

    readonly property color primary: "#97a8d1"
    readonly property color primaryContainer: "#434c5e"
    readonly property color primaryFixed: "#99aad1"
    readonly property color primaryFixedDim: "#97a8d1"
    readonly property color secondary: "#b692b1"
    readonly property color secondaryContainer: "#434c5e"
    readonly property color secondaryFixed: "#b894b3"
    readonly property color secondaryFixedDim: "#b692b1"
    readonly property color tertiary: "#95bcbb"
    readonly property color tertiaryContainer: "#434c5e"
    readonly property color tertiaryFixed: "#96bebd"
    readonly property color tertiaryFixedDim: "#95bcbb"

    readonly property color on_background: "#d8dee9"
    readonly property color on_surface: "#d8dee9"
    readonly property color on_surface_variant: "#aeb8c8"
    readonly property color on_primary: "#242933"
    readonly property color on_primary_container: "#d8dee9"
    readonly property color on_primary_fixed: "#242933"
    readonly property color on_primary_fixed_variant: "#aeb8c8"
    readonly property color on_secondary: "#242933"
    readonly property color on_secondary_container: "#d8dee9"
    readonly property color on_secondary_fixed: "#242933"
    readonly property color on_secondary_fixed_variant: "#aeb8c8"
    readonly property color on_tertiary: "#242933"
    readonly property color on_tertiary_container: "#d8dee9"
    readonly property color on_tertiary_fixed: "#242933"
    readonly property color on_tertiary_fixed_variant: "#aeb8c8"
    readonly property color inverseSurface: "#d8dee9"
    readonly property color inverse_on_surface: "#2e3440"
    readonly property color inversePrimary: "#8f9fc8"

    readonly property color outline: "#4c566a"
    readonly property color outlineVariant: "#4c566a"
    readonly property color shadow: "#242933"
    readonly property color scrim: "#242933"
    readonly property color error: "#c4686f"
    readonly property color errorContainer: "#b75059"
    readonly property color on_error: "#eceff4"
    readonly property color on_error_container: "#d8dee9"

    readonly property color sourceColor: "#631cbe"
    readonly property color warningColor: "#ebcb8b"
    readonly property color successColor: "#a3be8c"
}
